chore(deps): bump com.nimbusds:nimbus-jose-jwt from 10.2 to 10.3
Bumps [com.nimbusds:nimbus-jose-jwt](https://bitbucket.org/connect2id/nimbus-jose-jwt) from 10.2 to 10.3.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/CHANGELOG.txt">com.nimbusds:nimbus-jose-jwt's changelog</a>.</em></p>
<blockquote>
<p>10.2 (2025-04-07)
* Gson is made a direct instead of a shaded dependency to address module
issues introduced in 10.1 (iss <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
<p>10.3 (2025-05-09)
* Restores the Gson shading, adding placeholder interfaces to prevent
NoClassDefFoundError occurrences at runtime when the JAR is used on a
module path (iss <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/a988a2d5cdc9d5b55afc11a52f92232e67bc5697"><code>a988a2d</code></a> [maven-release-plugin] prepare for next development iteration</li>
<li><a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/5fa1dc9a25379500263ebc582cc1efa27b8101f4"><code>5fa1dc9</code></a> shade gson again</li>
<li><a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/800db7b1ab2d1d7b4171056112dc755a211115a1"><code>800db7b</code></a> Merged in feature/shaded-gson (pull request <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/127">#127</a>)</li>
<li><a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/f474bcfa68ef3f4bc5bc8fec37add01fa1f3d42a"><code>f474bcf</code></a> Adds change log entry for 10.3 (iss <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>)</li>
<li><a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/c1f3c4441041c0f625c989a6d0a97d77401c033e"><code>c1f3c44</code></a> [maven-release-plugin] prepare release 10.3</li>
<li>See full diff in <a href="https://bitbucket.org/connect2id/nimbus-jose-jwt/branches/compare/10.3..10.2">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.nimbusds:nimbus-jose-jwt&package-manager=gradle&previous-version=10.2&new-version=10.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>