fix oidc authentication with tgt timeout exp
When using OIDC authentication (i.e. implicit flow)
with the following configuration, we get an error
because OIDC expiration is based on
ExpirationPolicy#getTimeToLive() and not
getTimeToIdle().

For timeout policy, getTimeToIdle() is Long.MAX_VALUE.

Sample configuration:

```
cas:
  ticket:
    tgt:
      timeout:
        maxTimeToLiveInSeconds: 300
```

Error:

```
 2020-03-19 08:01:26,905 ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cas].[dispatcherServlet]] - <Servlet.service() for servlet [dispatcherServlet] in context with path [/cas] threw exception [Request processing failed; nested exception is java.lang.ArithmeticException: long overflow adding: 1584604886 + 9223372036854775807 = -9223372035270170923] with root cause>
 java.lang.ArithmeticException: long overflow adding: 1584604886 + 9223372036854775807 = -9223372035270170923
 	at org.jose4j.lang.Maths.add(Maths.java:13) ~[jose4j-0.7.0.jar:?]
 	at org.jose4j.jwt.NumericDate.addSeconds(NumericDate.java:61) ~[jose4j-0.7.0.jar:?]
 	at org.apereo.cas.oidc.token.OidcIdTokenGeneratorService.buildJwtClaims(OidcIdTokenGeneratorService.java:103) ~[cas-server-support-oidc-core-api-patch.jar:?]
```