chore(deps): bump okhttp3 from 4.12.0 to 5.0.0
Bumps `okhttp3` from 4.12.0 to 5.0.0.
Updates `com.squareup.okhttp3:logging-interceptor` from 4.12.0 to 5.0.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/square/okhttp/blob/master/CHANGELOG.md">com.squareup.okhttp3:logging-interceptor's changelog</a>.</em></p>
<blockquote>
<h2>Version 5.0.0</h2>
<p><em>2025-07-02</em></p>
<p>This is our first stable release of OkHttp since 2023. Here's the highlights if you're upgrading
from OkHttp 4.x:</p>
<p><strong>OkHttp is now packaged as separate JVM and Android artifacts.</strong> This allows us to offer
platform-specific features and optimizations. If your build system handles [Gradle module metadata],
this change should be automatic.</p>
<p><strong>MockWebServer has a new coordinate and package name.</strong> We didn’t like that our old artifact
depends on JUnit 4 so the new one doesn’t. It also has a better API built on immutable values. (We
intend to continue publishing the old <code>okhttp3.mockwebserver</code> artifact so there’s no urgency to
migrate.)</p>
<table>
<thead>
<tr>
<th align="left">Coordinate</th>
<th align="left">Package Name</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3:5.0.0</td>
<td align="left">mockwebserver3</td>
<td align="left">Core module. No JUnit dependency!</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit4:5.0.0</td>
<td align="left">mockwebserver3.junit4</td>
<td align="left">Optional JUnit 4 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit5:5.0.0</td>
<td align="left">mockwebserver3.junit5</td>
<td align="left">Optional JUnit 5 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver:5.0.0</td>
<td align="left">okhttp3.mockwebserver</td>
<td align="left">Obsolete. Depends on JUnit 4.</td>
</tr>
</tbody>
</table>
<p><strong>OkHttp now supports Happy Eyeballs ([RFC 8305][rfc_8305]) for IPv4+IPv6 networks.</strong> It attempts
both IPv6 and IPv4 connections concurrently, keeping whichever connects first.</p>
<p><strong>We’ve improved our Kotlin APIs.</strong> You can skip the builder:</p>
<pre lang="kotlin"><code>val request = Request(
  url = &quot;https://cash.app/&quot;.toHttpUrl(),
)
</code></pre>
<p><strong>OkHttp now supports [GraalVM].</strong></p>
<p>Here’s what has changed since 5.0.0-alpha.17:</p>
<ul>
<li>Upgrade: [Okio 3.15.0][okio_3_15_0].</li>
<li>Upgrade: [Kotlin 2.2.0][kotlin_2_2_0].</li>
<li>Fix: Don't crash with a <code>NoSuchMethodError</code> when using OkHttp with the Sentry SDK.</li>
<li>Fix: Retain the query data in the old <code>okhttp3.mockwebserver.RecordedRequest.path</code> property. We
inadvertently changed this behavior when we introduced the <code>mockwebserver3</code> API.</li>
</ul>
<h2>Version 5.0.0-alpha.17</h2>
<p><em>2025-06-29</em></p>
<p>This release stabilizes many APIs for the imminent OkHttp 5.0.0 release.</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/square/okhttp/commit/1b703d52a988222c4899c0bdf233db30f4f974c9"><code>1b703d5</code></a> Prepare for release 5.0.0.</li>
<li><a href="https://github.com/square/okhttp/commit/dcb640c3dada70207fe0f7e303ee7a9287c3d0db"><code>dcb640c</code></a> Fix breaking change from alpha.17 release (<a href="https://redirect.github.com/square/okhttp/issues/8899">#8899</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/75661d41cd2b4b014fc71320391c13a3a56d7946"><code>75661d4</code></a> Fix a NoSuchMethodError loading OkHttp on Android (<a href="https://redirect.github.com/square/okhttp/issues/8898">#8898</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/a84a09f0fa2e1ed5bd951950f88a4498f331bf6e"><code>a84a09f</code></a> Update com.squareup.okio to v3.15.0 (<a href="https://redirect.github.com/square/okhttp/issues/8896">#8896</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/06a88ad51f60e21ec91926cd0f85904d7d703a42"><code>06a88ad</code></a> Update dependency com.gradleup.shadow:shadow-gradle-plugin to v8.3.8 (<a href="https://redirect.github.com/square/okhttp/issues/8895">#8895</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/9ba896295a4e7ee82641e04d8cb65c72c461793b"><code>9ba8962</code></a> Document change of RecordedRequest.path</li>
<li><a href="https://github.com/square/okhttp/commit/2864541d51d9cf8bb8d9e7c0b4b7a172ff40f93c"><code>2864541</code></a> Update dependency com.puppycrawl.tools:checkstyle to v10.26.1 (<a href="https://redirect.github.com/square/okhttp/issues/8894">#8894</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/4309b5554e740913113e69286a253f945d1a15dd"><code>4309b55</code></a> Prepare next development version.</li>
<li><a href="https://github.com/square/okhttp/commit/ae1145c22dfb7ea68b1007b4afb8486f2bdafc2a"><code>ae1145c</code></a> Prepare for release 5.0.0-alpha.17.</li>
<li><a href="https://github.com/square/okhttp/commit/dba12fc5a6762574640b66949bd73be965464a71"><code>dba12fc</code></a> Update dependency de.mannodermaus.gradle.plugins:android-junit5 to v1.13.1.0 ...</li>
<li>Additional commits viewable in <a href="https://github.com/square/okhttp/compare/parent-4.12.0...parent-5.0.0">compare view</a></li>
</ul>
</details>
<br />

Updates `com.squareup.okhttp3:mockwebserver` from 4.12.0 to 5.0.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/square/okhttp/blob/master/CHANGELOG.md">com.squareup.okhttp3:mockwebserver's changelog</a>.</em></p>
<blockquote>
<h2>Version 5.0.0</h2>
<p><em>2025-07-02</em></p>
<p>This is our first stable release of OkHttp since 2023. Here's the highlights if you're upgrading
from OkHttp 4.x:</p>
<p><strong>OkHttp is now packaged as separate JVM and Android artifacts.</strong> This allows us to offer
platform-specific features and optimizations. If your build system handles [Gradle module metadata],
this change should be automatic.</p>
<p><strong>MockWebServer has a new coordinate and package name.</strong> We didn’t like that our old artifact
depends on JUnit 4 so the new one doesn’t. It also has a better API built on immutable values. (We
intend to continue publishing the old <code>okhttp3.mockwebserver</code> artifact so there’s no urgency to
migrate.)</p>
<table>
<thead>
<tr>
<th align="left">Coordinate</th>
<th align="left">Package Name</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3:5.0.0</td>
<td align="left">mockwebserver3</td>
<td align="left">Core module. No JUnit dependency!</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit4:5.0.0</td>
<td align="left">mockwebserver3.junit4</td>
<td align="left">Optional JUnit 4 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit5:5.0.0</td>
<td align="left">mockwebserver3.junit5</td>
<td align="left">Optional JUnit 5 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver:5.0.0</td>
<td align="left">okhttp3.mockwebserver</td>
<td align="left">Obsolete. Depends on JUnit 4.</td>
</tr>
</tbody>
</table>
<p><strong>OkHttp now supports Happy Eyeballs ([RFC 8305][rfc_8305]) for IPv4+IPv6 networks.</strong> It attempts
both IPv6 and IPv4 connections concurrently, keeping whichever connects first.</p>
<p><strong>We’ve improved our Kotlin APIs.</strong> You can skip the builder:</p>
<pre lang="kotlin"><code>val request = Request(
  url = &quot;https://cash.app/&quot;.toHttpUrl(),
)
</code></pre>
<p><strong>OkHttp now supports [GraalVM].</strong></p>
<p>Here’s what has changed since 5.0.0-alpha.17:</p>
<ul>
<li>Upgrade: [Okio 3.15.0][okio_3_15_0].</li>
<li>Upgrade: [Kotlin 2.2.0][kotlin_2_2_0].</li>
<li>Fix: Don't crash with a <code>NoSuchMethodError</code> when using OkHttp with the Sentry SDK.</li>
<li>Fix: Retain the query data in the old <code>okhttp3.mockwebserver.RecordedRequest.path</code> property. We
inadvertently changed this behavior when we introduced the <code>mockwebserver3</code> API.</li>
</ul>
<h2>Version 5.0.0-alpha.17</h2>
<p><em>2025-06-29</em></p>
<p>This release stabilizes many APIs for the imminent OkHttp 5.0.0 release.</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/square/okhttp/commit/1b703d52a988222c4899c0bdf233db30f4f974c9"><code>1b703d5</code></a> Prepare for release 5.0.0.</li>
<li><a href="https://github.com/square/okhttp/commit/dcb640c3dada70207fe0f7e303ee7a9287c3d0db"><code>dcb640c</code></a> Fix breaking change from alpha.17 release (<a href="https://redirect.github.com/square/okhttp/issues/8899">#8899</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/75661d41cd2b4b014fc71320391c13a3a56d7946"><code>75661d4</code></a> Fix a NoSuchMethodError loading OkHttp on Android (<a href="https://redirect.github.com/square/okhttp/issues/8898">#8898</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/a84a09f0fa2e1ed5bd951950f88a4498f331bf6e"><code>a84a09f</code></a> Update com.squareup.okio to v3.15.0 (<a href="https://redirect.github.com/square/okhttp/issues/8896">#8896</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/06a88ad51f60e21ec91926cd0f85904d7d703a42"><code>06a88ad</code></a> Update dependency com.gradleup.shadow:shadow-gradle-plugin to v8.3.8 (<a href="https://redirect.github.com/square/okhttp/issues/8895">#8895</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/9ba896295a4e7ee82641e04d8cb65c72c461793b"><code>9ba8962</code></a> Document change of RecordedRequest.path</li>
<li><a href="https://github.com/square/okhttp/commit/2864541d51d9cf8bb8d9e7c0b4b7a172ff40f93c"><code>2864541</code></a> Update dependency com.puppycrawl.tools:checkstyle to v10.26.1 (<a href="https://redirect.github.com/square/okhttp/issues/8894">#8894</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/4309b5554e740913113e69286a253f945d1a15dd"><code>4309b55</code></a> Prepare next development version.</li>
<li><a href="https://github.com/square/okhttp/commit/ae1145c22dfb7ea68b1007b4afb8486f2bdafc2a"><code>ae1145c</code></a> Prepare for release 5.0.0-alpha.17.</li>
<li><a href="https://github.com/square/okhttp/commit/dba12fc5a6762574640b66949bd73be965464a71"><code>dba12fc</code></a> Update dependency de.mannodermaus.gradle.plugins:android-junit5 to v1.13.1.0 ...</li>
<li>Additional commits viewable in <a href="https://github.com/square/okhttp/compare/parent-4.12.0...parent-5.0.0">compare view</a></li>
</ul>
</details>
<br />

Updates `com.squareup.okhttp3:okhttp` from 4.12.0 to 5.0.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/square/okhttp/blob/master/CHANGELOG.md">com.squareup.okhttp3:okhttp's changelog</a>.</em></p>
<blockquote>
<h2>Version 5.0.0</h2>
<p><em>2025-07-02</em></p>
<p>This is our first stable release of OkHttp since 2023. Here's the highlights if you're upgrading
from OkHttp 4.x:</p>
<p><strong>OkHttp is now packaged as separate JVM and Android artifacts.</strong> This allows us to offer
platform-specific features and optimizations. If your build system handles [Gradle module metadata],
this change should be automatic.</p>
<p><strong>MockWebServer has a new coordinate and package name.</strong> We didn’t like that our old artifact
depends on JUnit 4 so the new one doesn’t. It also has a better API built on immutable values. (We
intend to continue publishing the old <code>okhttp3.mockwebserver</code> artifact so there’s no urgency to
migrate.)</p>
<table>
<thead>
<tr>
<th align="left">Coordinate</th>
<th align="left">Package Name</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3:5.0.0</td>
<td align="left">mockwebserver3</td>
<td align="left">Core module. No JUnit dependency!</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit4:5.0.0</td>
<td align="left">mockwebserver3.junit4</td>
<td align="left">Optional JUnit 4 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver3-junit5:5.0.0</td>
<td align="left">mockwebserver3.junit5</td>
<td align="left">Optional JUnit 5 integration.</td>
</tr>
<tr>
<td align="left">com.squareup.okhttp3:mockwebserver:5.0.0</td>
<td align="left">okhttp3.mockwebserver</td>
<td align="left">Obsolete. Depends on JUnit 4.</td>
</tr>
</tbody>
</table>
<p><strong>OkHttp now supports Happy Eyeballs ([RFC 8305][rfc_8305]) for IPv4+IPv6 networks.</strong> It attempts
both IPv6 and IPv4 connections concurrently, keeping whichever connects first.</p>
<p><strong>We’ve improved our Kotlin APIs.</strong> You can skip the builder:</p>
<pre lang="kotlin"><code>val request = Request(
  url = &quot;https://cash.app/&quot;.toHttpUrl(),
)
</code></pre>
<p><strong>OkHttp now supports [GraalVM].</strong></p>
<p>Here’s what has changed since 5.0.0-alpha.17:</p>
<ul>
<li>Upgrade: [Okio 3.15.0][okio_3_15_0].</li>
<li>Upgrade: [Kotlin 2.2.0][kotlin_2_2_0].</li>
<li>Fix: Don't crash with a <code>NoSuchMethodError</code> when using OkHttp with the Sentry SDK.</li>
<li>Fix: Retain the query data in the old <code>okhttp3.mockwebserver.RecordedRequest.path</code> property. We
inadvertently changed this behavior when we introduced the <code>mockwebserver3</code> API.</li>
</ul>
<h2>Version 5.0.0-alpha.17</h2>
<p><em>2025-06-29</em></p>
<p>This release stabilizes many APIs for the imminent OkHttp 5.0.0 release.</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/square/okhttp/commit/1b703d52a988222c4899c0bdf233db30f4f974c9"><code>1b703d5</code></a> Prepare for release 5.0.0.</li>
<li><a href="https://github.com/square/okhttp/commit/dcb640c3dada70207fe0f7e303ee7a9287c3d0db"><code>dcb640c</code></a> Fix breaking change from alpha.17 release (<a href="https://redirect.github.com/square/okhttp/issues/8899">#8899</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/75661d41cd2b4b014fc71320391c13a3a56d7946"><code>75661d4</code></a> Fix a NoSuchMethodError loading OkHttp on Android (<a href="https://redirect.github.com/square/okhttp/issues/8898">#8898</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/a84a09f0fa2e1ed5bd951950f88a4498f331bf6e"><code>a84a09f</code></a> Update com.squareup.okio to v3.15.0 (<a href="https://redirect.github.com/square/okhttp/issues/8896">#8896</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/06a88ad51f60e21ec91926cd0f85904d7d703a42"><code>06a88ad</code></a> Update dependency com.gradleup.shadow:shadow-gradle-plugin to v8.3.8 (<a href="https://redirect.github.com/square/okhttp/issues/8895">#8895</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/9ba896295a4e7ee82641e04d8cb65c72c461793b"><code>9ba8962</code></a> Document change of RecordedRequest.path</li>
<li><a href="https://github.com/square/okhttp/commit/2864541d51d9cf8bb8d9e7c0b4b7a172ff40f93c"><code>2864541</code></a> Update dependency com.puppycrawl.tools:checkstyle to v10.26.1 (<a href="https://redirect.github.com/square/okhttp/issues/8894">#8894</a>)</li>
<li><a href="https://github.com/square/okhttp/commit/4309b5554e740913113e69286a253f945d1a15dd"><code>4309b55</code></a> Prepare next development version.</li>
<li><a href="https://github.com/square/okhttp/commit/ae1145c22dfb7ea68b1007b4afb8486f2bdafc2a"><code>ae1145c</code></a> Prepare for release 5.0.0-alpha.17.</li>
<li><a href="https://github.com/square/okhttp/commit/dba12fc5a6762574640b66949bd73be965464a71"><code>dba12fc</code></a> Update dependency de.mannodermaus.gradle.plugins:android-junit5 to v1.13.1.0 ...</li>
<li>Additional commits viewable in <a href="https://github.com/square/okhttp/compare/parent-4.12.0...parent-5.0.0">compare view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>