renovatebot(deps): update dependency org.springframework.boot:spring-boot-gradle-plugin to v3.2.1
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.springframework.boot:spring-boot-gradle-plugin](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `3.2.0` -> `3.2.1` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-gradle-plugin/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-gradle-plugin/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-gradle-plugin/3.2.0/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-gradle-plugin/3.2.0/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot (org.springframework.boot:spring-boot-gradle-plugin)</summary>

### [`v3.2.1`](https://togithub.com/spring-projects/spring-boot/releases/tag/v3.2.1)

#### :star: New Features

-   Cleanup java sources [#&#8203;38877](https://togithub.com/spring-projects/spring-boot/issues/38877)

#### :lady_beetle: Bug Fixes

-   HibernateJpaAutoConfiguration should be applied before DataSourceTransactionManagerAutoConfiguration [#&#8203;38880](https://togithub.com/spring-projects/spring-boot/issues/38880)
-   META-INF entries are duplicated under BOOT-INF/classes causing "Conflicting persistence unit definitions" error [#&#8203;38862](https://togithub.com/spring-projects/spring-boot/issues/38862)
-   logging.include-application-name has no effect when using log4j2 [#&#8203;38847](https://togithub.com/spring-projects/spring-boot/pull/38847)
-   Pulsar authentication param properties cause IllegalStateException with Pulsar Client 3.1.0  [#&#8203;38839](https://togithub.com/spring-projects/spring-boot/pull/38839)
-   Child context created with SpringApplicationBuilder runs parents runners [#&#8203;38837](https://togithub.com/spring-projects/spring-boot/issues/38837)
-   getSigners() info is lost for signed jars when using the new loader implementation with requiresUnpack [#&#8203;38833](https://togithub.com/spring-projects/spring-boot/issues/38833)
-   TestContainers parallel initialization doesn't work properly  [#&#8203;38831](https://togithub.com/spring-projects/spring-boot/issues/38831)
-   Zip file closed exceptions can be thrown due to StaticResourceJars closing jars from cached connections [#&#8203;38770](https://togithub.com/spring-projects/spring-boot/issues/38770)
-   Multi-byte filenames in zip files can cause an endless loop in ZipString.hash [#&#8203;38751](https://togithub.com/spring-projects/spring-boot/issues/38751)
-   Gradle task "bootJar" fails with "Failed to get permissions" when using Gradle 8.6-milestone-1 [#&#8203;38741](https://togithub.com/spring-projects/spring-boot/issues/38741)
-   Custom binding converters are ignored when working with collection types [#&#8203;38734](https://togithub.com/spring-projects/spring-boot/issues/38734)
-   WebFlux and resource server auto-configuration may fail due to null authentication manager [#&#8203;38713](https://togithub.com/spring-projects/spring-boot/issues/38713)
-   It is unclear that Docker Compose services have not been started as one or more is already running [#&#8203;38661](https://togithub.com/spring-projects/spring-boot/issues/38661)
-   Spring Boot jar launcher does not work in folders containing certain chars [#&#8203;38660](https://togithub.com/spring-projects/spring-boot/issues/38660)
-   FileNotFoundException is thrown eagerly from unused SSL bundles [#&#8203;38659](https://togithub.com/spring-projects/spring-boot/issues/38659)
-   NoUniqueBeanDefinitionFailureAnalyzer does not account for the fact that missing '-parameters' may be the cause [#&#8203;38652](https://togithub.com/spring-projects/spring-boot/issues/38652)
-   Traces are propagated if tracing is disabled [#&#8203;38641](https://togithub.com/spring-projects/spring-boot/issues/38641)
-   Missing registry auto-configuration for JMS listener observation support [#&#8203;38613](https://togithub.com/spring-projects/spring-boot/issues/38613)
-   Class loading fails on an interrupted thread causing com.mongodb.event.ServerClosedEvent to fail to load when Mongo detects a cluster change [#&#8203;38611](https://togithub.com/spring-projects/spring-boot/issues/38611)
-   Failures due to code not being compiled with '-parameters' are hard to identify [#&#8203;38603](https://togithub.com/spring-projects/spring-boot/issues/38603)
-   System SSL certificates are not used by the Apache HTTP Client in a RestTemplate built with RestTemplateBuilder [#&#8203;38600](https://togithub.com/spring-projects/spring-boot/issues/38600)
-   ZipFileSystem throws "java.util.zip.ZipException: read CEN tables failed" with certain nested jars [#&#8203;38595](https://togithub.com/spring-projects/spring-boot/issues/38595)
-   Nested jar URLs cannot be split and reassembled resulting in errors with projects that use this technique (such as JobRunr) [#&#8203;38592](https://togithub.com/spring-projects/spring-boot/issues/38592)
-   NoSuchMethodError can be thrown from Session.getCookie() due to binary incompatibilty [#&#8203;38589](https://togithub.com/spring-projects/spring-boot/issues/38589)
-   management.metrics.tags has been deprecated without a replacement working for all metrics [#&#8203;38583](https://togithub.com/spring-projects/spring-boot/issues/38583)
-   NegativeArraySizeException can be thrown from org.springframework.boot.loader.zip.ZipContent$Loader [#&#8203;38572](https://togithub.com/spring-projects/spring-boot/issues/38572)
-   Migration form 3.1.5 to 3.2.0 : "Default" Tracer is not provided in test anymore [#&#8203;38568](https://togithub.com/spring-projects/spring-boot/issues/38568)
-   TomcatWebServer stop doesn't close sockets for additional connectors [#&#8203;38564](https://togithub.com/spring-projects/spring-boot/issues/38564)
-   Port is already in use when using `@SpringBootTest` with a separate management port and a mock web environment [#&#8203;38554](https://togithub.com/spring-projects/spring-boot/issues/38554)
-   Keep-alive property causes processAot step to never finish [#&#8203;38531](https://togithub.com/spring-projects/spring-boot/issues/38531)
-   Setting 'spring.task.scheduling.shutdown.await-termination-period' does not result in a call to SimpleAsyncTaskScheduler#taskTerminationTimeout [#&#8203;38530](https://togithub.com/spring-projects/spring-boot/issues/38530)
-   Setting 'spring.task.execution.shutdown.await-termination-period' does not result in a call to SimpleAsyncTaskExecutor#taskTerminationTimeout [#&#8203;38528](https://togithub.com/spring-projects/spring-boot/issues/38528)
-   Nested URLs return null from classLoader.getResource("") causing ClassPathResource failures [#&#8203;38524](https://togithub.com/spring-projects/spring-boot/issues/38524)
-   Spring Boot 3.2 is not compatible with older versions of Liquibase [#&#8203;38522](https://togithub.com/spring-projects/spring-boot/issues/38522)
-   Controller level exceptions not getting populated in HTTP server requests metrics [#&#8203;33731](https://togithub.com/spring-projects/spring-boot/issues/33731)

#### :notebook_with_decorative_cover: Documentation

-   Fix typo [#&#8203;38879](https://togithub.com/spring-projects/spring-boot/issues/38879)
-   Add the LangChain4J Spring Boot Starter to the list of community starters [#&#8203;38776](https://togithub.com/spring-projects/spring-boot/pull/38776)
-   Document prerequisites for Docker Compose support [#&#8203;38764](https://togithub.com/spring-projects/spring-boot/issues/38764)
-   Update Dynatrace documentation links [#&#8203;38725](https://togithub.com/spring-projects/spring-boot/issues/38725)
-   Correct references to Jetty's HTTP2 server module [#&#8203;38632](https://togithub.com/spring-projects/spring-boot/pull/38632)
-   Fix Observation Filter docs [#&#8203;38586](https://togithub.com/spring-projects/spring-boot/issues/38586)
-   Reinstate mention of testAndDevelopmentOnly when using Testcontainers at dev time [#&#8203;38571](https://togithub.com/spring-projects/spring-boot/issues/38571)

#### :hammer: Dependency Upgrades

-   Upgrade to AspectJ 1.9.21 [#&#8203;38797](https://togithub.com/spring-projects/spring-boot/issues/38797)
-   Upgrade to Dropwizard Metrics 4.2.23 [#&#8203;38798](https://togithub.com/spring-projects/spring-boot/issues/38798)
-   Upgrade to Groovy 4.0.16 [#&#8203;38799](https://togithub.com/spring-projects/spring-boot/issues/38799)
-   Upgrade to Hibernate 6.4.1.Final [#&#8203;38870](https://togithub.com/spring-projects/spring-boot/issues/38870)
-   Upgrade to HttpClient5 5.2.3 [#&#8203;38800](https://togithub.com/spring-projects/spring-boot/issues/38800)
-   Upgrade to HttpCore5 5.2.4 [#&#8203;38801](https://togithub.com/spring-projects/spring-boot/issues/38801)
-   Upgrade to Janino 3.1.11 [#&#8203;38802](https://togithub.com/spring-projects/spring-boot/issues/38802)
-   Upgrade to Jaybird 5.0.3.java11 [#&#8203;38803](https://togithub.com/spring-projects/spring-boot/issues/38803)
-   Upgrade to Jersey 3.1.5 [#&#8203;38804](https://togithub.com/spring-projects/spring-boot/issues/38804)
-   Upgrade to Jetty 12.0.5 [#&#8203;38871](https://togithub.com/spring-projects/spring-boot/issues/38871)
-   Upgrade to Kafka 3.6.1 [#&#8203;38806](https://togithub.com/spring-projects/spring-boot/issues/38806)
-   Upgrade to Kotlin 1.9.21 [#&#8203;38807](https://togithub.com/spring-projects/spring-boot/issues/38807)
-   Upgrade to Kotlin Serialization 1.6.2 [#&#8203;38808](https://togithub.com/spring-projects/spring-boot/issues/38808)
-   Upgrade to Logback 1.4.14 [#&#8203;38809](https://togithub.com/spring-projects/spring-boot/issues/38809)
-   Upgrade to Maven Javadoc Plugin 3.6.3 [#&#8203;38810](https://togithub.com/spring-projects/spring-boot/issues/38810)
-   Upgrade to Micrometer 1.12.1 [#&#8203;38693](https://togithub.com/spring-projects/spring-boot/issues/38693)
-   Upgrade to Micrometer Tracing 1.2.1 [#&#8203;38694](https://togithub.com/spring-projects/spring-boot/issues/38694)
-   Upgrade to Netty 4.1.104.Final [#&#8203;38872](https://togithub.com/spring-projects/spring-boot/issues/38872)
-   Upgrade to Pulsar Reactive 0.5.1 [#&#8203;38873](https://togithub.com/spring-projects/spring-boot/issues/38873)
-   Upgrade to R2DBC Postgresql 1.0.3.RELEASE [#&#8203;38812](https://togithub.com/spring-projects/spring-boot/issues/38812)
-   Upgrade to R2DBC Proxy 1.1.3.RELEASE [#&#8203;38813](https://togithub.com/spring-projects/spring-boot/issues/38813)
-   Upgrade to Reactor Bom 2023.0.1 [#&#8203;38695](https://togithub.com/spring-projects/spring-boot/issues/38695)
-   Upgrade to Spring AMQP 3.1.1 [#&#8203;38860](https://togithub.com/spring-projects/spring-boot/issues/38860)
-   Upgrade to Spring Authorization Server 1.2.1 [#&#8203;38696](https://togithub.com/spring-projects/spring-boot/issues/38696)
-   Upgrade to Spring Data Bom 2023.1.1 [#&#8203;38697](https://togithub.com/spring-projects/spring-boot/issues/38697)
-   Upgrade to Spring Framework 6.1.2 [#&#8203;38814](https://togithub.com/spring-projects/spring-boot/issues/38814)
-   Upgrade to Spring Integration 6.2.1 [#&#8203;38698](https://togithub.com/spring-projects/spring-boot/issues/38698)
-   Upgrade to Spring Kafka 3.1.1 [#&#8203;38874](https://togithub.com/spring-projects/spring-boot/issues/38874)
-   Upgrade to Spring LDAP 3.2.1 [#&#8203;38699](https://togithub.com/spring-projects/spring-boot/issues/38699)
-   Upgrade to Spring Pulsar 1.0.1 [#&#8203;38875](https://togithub.com/spring-projects/spring-boot/issues/38875)
-   Upgrade to Spring Retry 2.0.5 [#&#8203;38836](https://togithub.com/spring-projects/spring-boot/issues/38836)
-   Upgrade to Spring Security 6.2.1 [#&#8203;38700](https://togithub.com/spring-projects/spring-boot/issues/38700)
-   Upgrade to Spring Session 3.2.1 [#&#8203;38866](https://togithub.com/spring-projects/spring-boot/issues/38866)
-   Upgrade to Spring WS 4.0.9 [#&#8203;38876](https://togithub.com/spring-projects/spring-boot/issues/38876)
-   Upgrade to Tomcat 10.1.17 [#&#8203;38815](https://togithub.com/spring-projects/spring-boot/issues/38815)
-   Upgrade to UnboundID LDAPSDK 6.0.11 [#&#8203;38816](https://togithub.com/spring-projects/spring-boot/issues/38816)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;SandraAhlgrimm](https://togithub.com/SandraAhlgrimm), [@&#8203;aleksandrserbin](https://togithub.com/aleksandrserbin), [@&#8203;cachescrubber](https://togithub.com/cachescrubber), [@&#8203;dependabot](https://togithub.com/dependabot)\[bot], [@&#8203;gavlyukovskiy](https://togithub.com/gavlyukovskiy), [@&#8203;ilies-bel](https://togithub.com/ilies-bel), [@&#8203;meiyese](https://togithub.com/meiyese), [@&#8203;onobc](https://togithub.com/onobc), [@&#8203;pirgeo](https://togithub.com/pirgeo), [@&#8203;quaff](https://togithub.com/quaff), [@&#8203;shin-mallang](https://togithub.com/shin-mallang), and [@&#8203;tomfrenken](https://togithub.com/tomfrenken)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 10pm every weekday,before 6am every weekday" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/apereo/cas).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMDMuMSIsInVwZGF0ZWRJblZlciI6IjM3LjEwMy4xIiwidGFyZ2V0QnJhbmNoIjoibWFzdGVyIn0=-->