renovatebot(deps): update dependency io.lettuce:lettuce-core to v6.7.1.release
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [io.lettuce:lettuce-core](https://redirect.github.com/redis/lettuce) | dependencies | patch | `6.7.0.RELEASE` -> `6.7.1.RELEASE` |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>redis/lettuce (io.lettuce:lettuce-core)</summary>

### [`v6.7.1.RELEASE`](https://redirect.github.com/redis/lettuce/releases/tag/6.7.1.RELEASE)

[Compare Source](https://redirect.github.com/redis/lettuce/compare/6.7.0.RELEASE...6.7.1.RELEASE)

The Lettuce team is pleased to announce the Lettuce 6.7.1 service release!
This release ships with bugfixes and dependency upgrades.

Lettuce 6 supports Redis 2.6+ up to Redis 7.x. In terms of Java runtime, Lettuce requires
at least Java 8 and works with Java 21.

Thanks to all contributors who made Lettuce 6.7.1 possible.

### :green_book: Links

-   Reference documentation: https://lettuce.io/core/6.7.1.RELEASE/reference/
-   Javadoc: https://lettuce.io/core/6.7.1.RELEASE/api/

#### :lady_beetle: Bug Fixes

-   NoClassDefFoundError in Lettuce 6.7.0 [#&#8203;3317](https://redirect.github.com/redis/lettuce/issues/3317) by [@&#8203;tishun](https://redirect.github.com/tishun) in [https://github.com/redis/lettuce/pull/3319](https://redirect.github.com/redis/lettuce/pull/3319)

**Full Changelog**: https://github.com/redis/lettuce/compare/6.5.3.RELEASE...6.5.4.RELEASE

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 5pm,before 9am" in timezone America/Los_Angeles, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC40MS4wIiwidXBkYXRlZEluVmVyIjoiNDAuNDEuMCIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6WyJCb3QiLCJSZW5vdmF0ZSJdfQ==-->